plugin-settings:
  plugin-prefix: "&e&lArcade &8| "
  no-permission: "&cNo permission."
  config-reloaded: "%prefix% &aSuccessfully reloaded the configuration file"
blockbreaker-config:
  game-prefix: "&c&lBlock Breaker"
  winning-player-message: "&e%player% &6WINS!"
  playing-arena: "&aYou're now playing in arena:"
  not-in-arena: "&cYou are not in an arena"
  required-players: 2
  countdown-seconds: 60
  gametime-length: 120
  game-forcestart-messages:
    force-start: "%prefix% &aForce started a game of BlockBreaker"
  countdown-messages:
    waiting-message: "&cWaiting for %players_needed% players to start the game"
    not-enough-players: "&7There are not enough players to start"
    countdown-1-seconds: "&aGame will start in &21&a seconds"
    game-start-message:
      - "&7"
      - "&7Welcome to &c&lBlockBreaker"
      - ""
      - "&7Your objective is to break as many blocks"
      - "&7as you can before the time limit"
      - ""
      - "&7The player with the most broken blocks wins."
  lobby-spawn:
    world: 'world'
    x: 10
    y: 100
    z: 10
    pitch: 0
    yaw: 0
  arenas:
    '0':
      world: 'world'
      x: 10
      y: 100
      z: 10
      pitch: 0
      yaw: 0
    '1':
      world:
      x:
      y:
      z:
      pitch:
      yaw: