name: ArcadeUtils
version: ${project.version}
main: me.buryings.arcadeutils.ArcadeUtils
description: Arcade server utilities
commands:
  arcade:
    description: Base command and lists plugin version
  arcadereload:
    description: Reloads config file
  menu:
    description: Opens main arcade menu
